// attempted on 13th February 2023

#include <stdio.h>
int main() {    

    float principal, rate, time, SI;
    
    printf("Enter the principal amount deposited: ");
    scanf("%f", &principal);
    
    printf("Enter the rate: ");
    scanf("%f", &rate);
    
    printf("Enter the time for which the principal is deposited: ");
    scanf("%f", &time);

    SI = principal * rate * time / 100;      
    
    printf("The simple interest generated by depositing %f for %f amount of time (in years) at the rate of %f is %f", principal, rate, time, SI);
    return 0;
}
